#!/bin/bash -v

#
# ROM build script
#
# Copyright (C) 2017-2018 @rockinroyle aka Ralph L Royle III
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/> 

# ROM Build script

USAGE=" `basename $0` [-c|-d] [device]"

# Source helper script with functions that reduce script size

. functions.sh
. helper

# Check proper script usage before running

if [$# -lt 2]; then
	printUSAGE
	exit 1
fi

case "$1" in
	-c)rm -rf "$HOME"/.ccache 
	   make clobber 
	   brunch "$2"
	   ;;
	-d)brunch "$2"
	 *)printUSAGE
	   break
	   ;;
	   exit
esac

exit
