#!/bin/bash

# NoobBuilds ROM Build script

export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx4g"
./prebuilts/sdk/tools/jack-admin kill-server
./prebuilts/sdk/tools/jack-admin start-server
export USE_CCACHE=1
export ENV='build/envsetup.sh'
DEVICE=('shamu' 'angler' 'flounder')
export PS3="Please make a selection ====> "

source "$ENV"

echo ' '
echo '************************************************************************'
echo '* Would you like to clobber output directory? Yes/No? Select a number: *'
echo '************************************************************************'

select CLEAN in Yes No
do
	case "$CLEAN" in
	     Yes) make clobber
	          break
	          ;;
	     No) break;;
	     *) echo "Please choose yes or no. Invalid selection, $REPLY.";;
	esac
done

echo ' '
echo '**********************************************'
echo '* Choose a device to build? Select a number: *'
echo '**********************************************'

select BUILD in "${DEVICE[0]}" "${DEVICE[1]}" "${DEVICE[2]}"
do
	case "$BUILD" in
	     "${DEVICE[0]}"|"${DEVICE[1]}"|"${DEVICE[2]}") brunch "$BUILD"
	                                                   break
	                                                   ;;
	     *) echo "Please choose a device from the list. Invalid selection, $REPLY.";;
	esac
done
exit

